branches:
  except: /^v\d/
language: node_js
node_js: node
env:
  global:
    secure: Z2yRM8s2BMVkgZ5nDDQB+SiJ3dJH806CZouUynLF4pl4zVDZgpgRxPNdi6l7tfLlr+HAZQYgWwW9pzrQfX3lX1hvVbRUTeTDXn6PQM+pvCGZQgmGl7UWc1NpM++pPcCCq9IPiwfl30LQxWh8xwIzJ5RDGHFlD4O9T0fy3gkHbJM=
before_script:
  - git config --global user.name "John Doe"
  - git config --global user.email johndoe@example.org
matrix:
  include:
  - after_script: node_modules/.bin/nyc report | npx coveralls
